const TYPE_COLORS = {
  '노말': '#A8A878',
  '격투': '#C03028',
  '페어리': '#EE99AC',
  '강철': '#B8B8D0',
  '에스퍼': '#F85888',
  '고스트': '#705898',
  '땅': '#E0C068',
  '드래곤': '#7038F8',
  '전기': '#F8D030',
  '번개': '#F8D030',
  '—': '#999',
};

/** 포켓몬 TCG 등급 표기 */
const RARITY_SYMBOL = { N: '●', R: '◆', SR: '★', UR: '★★', MISS: '—' };
const RARITY_GRADE = { N: 'C', R: 'U', SR: 'R', UR: 'RR', MISS: '—' };
const STAGE_LABEL = { N: '기본', R: '1진화', SR: '레어', UR: 'ex', MISS: '' };

function getStage(card) {
  return card.stage || STAGE_LABEL[card.rarity] || '기본';
}

function getRarityLine(rarity) {
  return `${RARITY_SYMBOL[rarity] || ''} ${RARITY_GRADE[rarity] || rarity}`.trim();
}

const CARD_POOL = [
  {
    id: 'yeveee-basic',
    name: '유설아',
    stage: '기본',
    rarity: 'N',
    type: '노말',
    hp: 80,
    attack: '츄르 던지기',
    damage: 30,
    energy: 1,
    desc: 'SOOP에서 활동하는 버추얼 스트리머. 게임 방송의 달인!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '001',
  },
  {
    id: 'yeveee-smile',
    name: '유설아',
    stage: '기본',
    rarity: 'N',
    type: '노말',
    hp: 70,
    attack: '궁디 반짝',
    damage: 25,
    energy: 1,
    desc: '궁디반장의 미소가 상대를 녹인다.',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '002',
  },
  {
    id: 'yeveee-vworld',
    name: '유설아',
    stage: '기본',
    rarity: 'N',
    type: '페어리',
    hp: 90,
    attack: '버추얼 펀치',
    damage: 35,
    energy: 2,
    desc: 'VWORLD 공식 프로필. 타격감 좋은 콤보!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    no: '003',
  },
  {
    id: 'yeveee-game',
    name: '유설아',
    stage: '1진화',
    rarity: 'R',
    type: '격투',
    hp: 110,
    attack: '타격감 MAX',
    damage: 50,
    energy: 2,
    desc: '게임 위주 방송! 케미 폭발!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '004',
  },
  {
    id: 'yeveee-burger',
    name: '유설아',
    stage: '1진화',
    rarity: 'R',
    type: '격투',
    hp: 120,
    attack: '궁디 임팩트',
    damage: 55,
    energy: 2,
    desc: '별명 궁디반장! 강력한 한 방!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '005',
  },
  {
    id: 'yeveee-burgercom',
    name: '유설아',
    stage: '1진화',
    rarity: 'R',
    type: '강철',
    hp: 130,
    attack: '종겜 스매시',
    damage: 60,
    energy: 3,
    desc: '버컴퍼니 멤버! 종합게임의 여왕!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    no: '006',
  },
  {
    id: 'yeveee-chur',
    name: '유설아',
    stage: '레어',
    rarity: 'SR',
    type: '에스퍼',
    hp: 140,
    attack: '츄르단 하트',
    damage: 70,
    energy: 2,
    desc: '팬덤 츄르단의 사랑이 모인 카드!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '007',
  },
  {
    id: 'yeveee-heupsung',
    name: '유설아',
    stage: '레어',
    rarity: 'SR',
    type: '고스트',
    hp: 150,
    attack: '흡성 프레임',
    damage: 80,
    energy: 3,
    desc: '흡성 프레임 씌워진 전설의 순간!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    no: '008',
  },
  {
    id: 'yeveee-mark',
    name: '유설아',
    stage: '레어',
    rarity: 'SR',
    type: '땅',
    hp: 145,
    attack: '블록 파괴',
    damage: 75,
    energy: 2,
    desc: '감체스터 마크 크루 출신! 블록도 부순다!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    no: '009',
  },
  {
    id: 'yeveee-legend',
    name: '유설아 ex',
    stage: 'ex',
    rarity: 'UR',
    type: '드래곤',
    hp: 200,
    attack: '츄르단 EX',
    damage: 120,
    energy: 3,
    desc: '전설의 SOOP 스트리머. 2018 데뷔!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    holo: true,
    no: '010',
  },
  {
    id: 'yeveee-god',
    name: '유설아 ex',
    stage: 'ex',
    rarity: 'UR',
    type: '전기',
    hp: 220,
    attack: '별풍 콤보',
    damage: 150,
    energy: 4,
    desc: '최희귀 GOD 카드.',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    holo: true,
    no: '011',
  },
  {
    id: 'yeveee-shiny',
    name: '유설아 ★',
    stage: 'ex',
    rarity: 'UR',
    type: '번개',
    hp: 180,
    attack: '이색 변이',
    damage: 100,
    energy: 3,
    desc: '색이 다른 희귀 변이!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    holo: true,
    no: '012',
  },
];

const MISS_CARD = {
  id: 'miss',
  name: '꽝',
  stage: '',
  rarity: 'MISS',
  type: '—',
  hp: 0,
  attack: '—',
  damage: 0,
  energy: 0,
  desc: '아무것도 나오지 않았다...',
  image: null,
  no: '—',
};

/** 등급별 가중치 (합 100) */
const RARITY_WEIGHTS = {
  UR: 1,
  SR: 5,
  R: 15,
  N: 50,
  MISS: 29,
};

const RARITY_LABELS = {
  UR: 'RR',
  SR: 'R',
  R: 'U',
  N: 'C',
  MISS: '—',
};

const RARITY_COLORS = {
  UR: '#FFD700',
  SR: '#C77DFF',
  R: '#4CC9F0',
  N: '#ADB5BD',
  MISS: '#6C757D',
};
