/** 유설아 카드 데이터 — 공개 프로필 이미지 사용 */
const CARD_POOL = [
  {
    id: 'yeveee-basic',
    name: '유설아',
    subtitle: '기본형',
    rarity: 'N',
    type: '노말',
    hp: 80,
    attack: '츄르 던지기',
    damage: 30,
    desc: 'SOOP에서 활동하는 버추얼 스트리머. 게임 방송의 달인!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'none',
  },
  {
    id: 'yeveee-smile',
    name: '유설아',
    subtitle: '미소',
    rarity: 'N',
    type: '노말',
    hp: 70,
    attack: '궁디 반짝',
    damage: 25,
    desc: '궁디반장의 미소가 상대를 녹인다.',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'brightness(1.1) saturate(1.2)',
  },
  {
    id: 'yeveee-vworld',
    name: '유설아',
    subtitle: 'VWORLD',
    rarity: 'N',
    type: '페어리',
    hp: 90,
    attack: '버추얼 펀치',
    damage: 35,
    desc: 'VWORLD 공식 프로필. 타격감 좋은 콤보!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    filter: 'none',
  },
  {
    id: 'yeveee-game',
    name: '유설아',
    subtitle: '게임 모드',
    rarity: 'R',
    type: '격투',
    hp: 110,
    attack: '타격감 MAX',
    damage: 50,
    desc: '게임 위주 방송! 케미 폭발!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'hue-rotate(30deg) contrast(1.1)',
  },
  {
    id: 'yeveee-burger',
    name: '유설아',
    subtitle: '궁디반장',
    rarity: 'R',
    type: '격투',
    hp: 120,
    attack: '궁디 임팩트',
    damage: 55,
    desc: '별명 궁디반장! 강력한 한 방!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'sepia(0.3) saturate(1.4)',
  },
  {
    id: 'yeveee-burgercom',
    name: '유설아',
    subtitle: '버컴퍼니',
    rarity: 'R',
    type: '강철',
    hp: 130,
    attack: '종겜 스매시',
    damage: 60,
    desc: '버컴퍼니 멤버! 종합게임의 여왕!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    filter: 'hue-rotate(200deg) brightness(1.05)',
  },
  {
    id: 'yeveee-chur',
    name: '유설아',
    subtitle: '츄르단',
    rarity: 'SR',
    type: '에스퍼',
    hp: 140,
    attack: '츄르단 하트',
    damage: 70,
    desc: '팬덤 츄르단의 사랑이 모인 카드!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'hue-rotate(280deg) saturate(1.5) brightness(1.1)',
  },
  {
    id: 'yeveee-heupsung',
    name: '유설아',
    subtitle: '흡성',
    rarity: 'SR',
    type: '고스트',
    hp: 150,
    attack: '흡성 프레임',
    damage: 80,
    desc: '흡성 프레임 씌워진 전설의 순간!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    filter: 'hue-rotate(260deg) contrast(1.2) brightness(0.95)',
  },
  {
    id: 'yeveee-mark',
    name: '유설아',
    subtitle: '마크 크루',
    rarity: 'SR',
    type: '땅',
    hp: 145,
    attack: '블록 파괴',
    damage: 75,
    desc: '감체스터 마크 크루 출신! 블록도 부순다!',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'sepia(0.5) hue-rotate(40deg)',
  },
  {
    id: 'yeveee-legend',
    name: '유설아♡',
    subtitle: '레전드',
    rarity: 'UR',
    type: '드래곤',
    hp: 200,
    attack: '츄르단 EX',
    damage: 120,
    desc: '★ 전설의 SOOP 스트리머 ★ 2018 데뷔!',
    image: 'https://d1b4su7rx1qs3y.cloudfront.net/uploads/images/JYgjMHUbLMWQ.png',
    filter: 'saturate(1.6) brightness(1.15) contrast(1.1)',
    holo: true,
  },
  {
    id: 'yeveee-god',
    name: '유설아♡',
    subtitle: 'GOD',
    rarity: 'UR',
    type: '전기',
    hp: 220,
    attack: '별풍 콤보',
    damage: 150,
    desc: '★★★ 최희귀 GOD 카드 ★★★',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'hue-rotate(45deg) saturate(2) brightness(1.2)',
    holo: true,
  },
  {
    id: 'yeveee-shiny',
    name: '유설아',
    subtitle: 'SHINY',
    rarity: 'UR',
    type: '번개',
    hp: 180,
    attack: '이색 변이',
    damage: 100,
    desc: '✨ 색이 다른 희귀 변이! ✨',
    image: 'https://profile.img.sooplive.co.kr/LOGO/ye/yeveee/yeveee.jpg',
    filter: 'hue-rotate(180deg) saturate(1.8) brightness(1.3)',
    holo: true,
  },
];

const MISS_CARD = {
  id: 'miss',
  name: '꽝',
  subtitle: '빈 카드',
  rarity: 'MISS',
  type: '—',
  hp: 0,
  attack: '—',
  damage: 0,
  desc: '아무것도 나오지 않았다...',
  image: null,
  filter: 'none',
};

/** 등급별 가중치 (합 100) */
const RARITY_WEIGHTS = {
  UR: 1,
  SR: 5,
  R: 15,
  N: 50,
  MISS: 29,
};

const RARITY_LABELS = {
  UR: '전설',
  SR: '희귀',
  R: '고급',
  N: '일반',
  MISS: '꽝',
};

const RARITY_COLORS = {
  UR: '#FFD700',
  SR: '#C77DFF',
  R: '#4CC9F0',
  N: '#ADB5BD',
  MISS: '#6C757D',
};
